name: Build Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        build_type: [ Release, Debug ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dependencies [Windows]
      if: runner.os == 'Windows'
      run: |
        echo "Fixing vendored zlib finding on 64-bit CI..."
        for lib in zlib{,d}; do
          mv -v libs/lib/$lib{64,}.lib
        done

    - name: Dependencies [macOS]
      if: runner.os == 'macOS'
      run: |
        export HOMEBREW_NO_INSTALL_CLEANUP=1
        brew update
        brew install libao

    - name: Dependencies [Linux]
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install \
          libasound2-dev \
          libpulse-dev \
          libao-dev \
          zlib1g-dev \

    - name: Configuring
      run: |
        cmake \
          -B ${GITHUB_WORKSPACE}/build \
          -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/install \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DBUILD_TESTS=ON \

    - name: Build
      run: |
        cmake \
          --build ${GITHUB_WORKSPACE}/build \
          --config ${{ matrix.build_type }} \
          --parallel 2 \

    - name: Install
      run: |
        cmake \
          --install ${GITHUB_WORKSPACE}/build \

    - name: Check
      run: |
        echo "Listing what we installed"
        echo "========================="
        find ${GITHUB_WORKSPACE}/install
        echo ""
        
        echo "Listing pkg-config file contents"
        echo "================================"
        for pc in ${GITHUB_WORKSPACE}/install/lib/pkgconfig/*.pc; do
          echo $(basename "$pc")
          cat "$pc"
          echo ""
        done
