name: Build Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        build_type: [ Release, Debug ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dependencies [Linux]
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install \
          libasound2-dev \
          libpulse-dev \
          libao-dev \
          zlib1g-dev \

    - name: Configuring
      run: |
        cmake \
          -B ${{ github.workspace }}/build \
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DBUILD_TESTS=ON \

    - name: Build
      run: |
        make \
          -C ${{github.workspace}}/build \
          -j2

    - name: Install
      run: |
        make \
          -C ${{github.workspace}}/build \
          install

    - name: Check
      run: |
        echo "Listing what we installed"
        echo "========================="
        find ${{github.workspace}}/install
        echo ""
        
        echo "Listing pkg-config file contents"
        echo "================================"
        for pc in ${{github.workspace}}/install/lib/pkg-config/*.pc; do
          echo $(basename "$pc")
          cat "$pc"
        done
